name: scan C code brpc
on: # yamllint disable-line rule:truthy
  workflow_dispatch:

permissions: write-all

jobs:
  test-scan-c-code-brpc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout_target
        uses: actions/checkout@v4
      - name: use action to generate suggestion for deployment settings
        id: Lint_with_LLM
        uses: SamYuan1990/OpenAI_CodeAgent-action@main
        with:
          baseURL: https://api.deepseek.com
          apiKey: ${{ secrets.API_KEY }}
          model: deepseek-chat
          dirpath: '/workdir/src/brpc'
          runType: ccodescan
          maxIterations: 970
          dryRun: true
      - name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: dist_brpc_c
          path: |
            GenAI_output

  test-scan-dep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout_target
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: generate CVE.json
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b ./
          go install github.com/devops-kung-fu/bomber@latest 
          ./syft scan .  --select-catalogers "c++" -o cyclonedx-json -vv  > sbom.json 
          cat sbom.json
          bomber scan ./sbom.json --output=json --debug > cve.json
          cat cve.json
      - name: use action to generate suggestion for deployment settings
        id: Lint_with_LLM
        uses: SamYuan1990/OpenAI_CodeAgent-action@main
        with:
          baseURL: https://api.deepseek.com
          apiKey: ${{ secrets.API_KEY }}
          model: deepseek-chat
          dirpath: '/workdir/src/'
          runType: CVEDependency
          dryRun: true
      - name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: dist_brpc_cve
          path: |
            cve.json
            GenAI_output
